usc/CFR/urls.py
from django.urls import path

from . import views
from django.conf import settings


app_name = settings.CFR

urlpatterns = [
    path(
        f'collection/{settings.CFR}/',
        views.CollectionView.as_view(), name='collection'),

    path(
        f'{settings.CFR}/<str:slug_id>/',
        views.NodeView.as_view(), name='node'),

    path(
        f'{settings.CFR}/<str:slug_id>/html/',
        views.Content.as_view(), name='html'),
]

usc/Main/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views


app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.FullTextSearch.as_view(), name='search'),
    path('update-cookies/', views.update_cookies, name='update_cookies'),

    path(
        'terms-of-use/',
        TemplateView.as_view(template_name='Main/terms_of_use.html'),
        name='terms_of_use'
    ),
    path(
        'terms-of-service/',
        TemplateView.as_view(template_name='Main/terms_of_service.html'),
        name='terms_of_service'
    ),
    path(
        'privacy-policy/',
        TemplateView.as_view(template_name='Main/privacy_policy.html'),
        name='privacy_policy'
    ),
]

usc/account/urls.py
from django.urls import path

from . import views


app_name = 'account'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('register/', views.RegisterPage.as_view(), name='register'),
    path('logout/', views.Logout, name='logout'),
    path('notify/<str:alert_key>/', views.alert_box, name='alert'),

    path('profile/', views.ProfileView.as_view(), name='profile'),
    path(
        'profile/update/',
        views.ProfileUpdate.as_view(), name='profile_update'),

    path(
        'change-password/',
        views.ChangePassword.as_view(), name='change_password'),
    path("activate/<slug:uidb64>/<slug:token>/",
         views.activate_email, name="activate"),

    path('forget-password/', views.ForgetPasswordView.as_view(),
         name='forget_password'),
    path('reset/<slug:uidb64>/<slug:token>/',
         views.ResetPasswordVerify.as_view(), name='password_reset_confirm'),
    path('resend-email-verification/',
         views.ResendEmailVerificationLink.as_view(),
         name='resend_verification'),
]

usc/Main/models.py
from django.db import models


class PlaceholderInput(models.Model):
    name = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

usc/Main/views.py
from threading import Thread
from typing import Union

from CFR.models import CFRNode, CFRNodeManager
from django.conf import settings
from django.shortcuts import render, redirect
from django.views.decorators.cache import cache_page
from USCODE.models import Node, NodeManager
from utils.ai_query import ai_query
from django.views.generic import TemplateView
from django.contrib import messages
from utils.general import remove_session

QA = "QA"


@cache_page(5)
def index(request):
    """Show collections available"""
    context = {
        "collections": [
            {
                "name": "CFR - Code of Federal Regulations",
                "code": settings.CFR,
            },
            {
                "name": "USCS - United States Code Service",
                "code": settings.USCODE,
            },
        ]
    }
    return render(request, 'Main/index.html', context)


def update_cookies(request):
    if request.POST:
        accept = request.POST.get('accept')
        if accept == 'true':
            remove_session(request, settings.DISABLE_COOKIES)
            messages.success(request, "Cookies enabled")
            return redirect(request.META.get("HTTP_REFERER", "/"))
        elif accept == 'false':
            request.session[settings.DISABLE_COOKIES] = True
            messages.success(request, "Cookies disabled")
            return redirect(request.META.get("HTTP_REFERER", "/"))

    return redirect(request.META.get("HTTP_REFERER", "/"))


def make_qa(query: str):
    return ai_query(query).lstrip("?")


def get_qa(query, datax: dict):
    try:
        qa = make_qa(query)
    except Exception:
        qa = "Error generating answer"
    datax["qa"] = qa


def get_cfr(query, datax: dict):
    cfr_results = CFRNode.objects.full_text_search(query)
    datax["cfr"] = cfr_results


def get_usc(query, datax: dict):
    usc_results = Node.objects.full_text_search(query)
    datax["usc"] = usc_results


AI_TERM_SESSION_KEY = "ai_term_accepted"


class FullTextSearch(TemplateView):
    template_name = "Main/search.html"

    def get(self, request, *args, **kwargs):
        context = {}

        display_qa = True

        # check if user has accepted cookies
        if request.session.get(settings.DISABLE_COOKIES):
            messages.warning(
                request,
                'Please enable cookies to get the best \
experience using this site. You can disable cookies later.')
            display_qa = False

        # Check if the user as accepted AI generated answers term
        context[AI_TERM_SESSION_KEY] = request.session.get(
            AI_TERM_SESSION_KEY, False)

        query = request.GET.get("search")
        collection = request.GET.get("collection")

        if query:
            if collection == '':
                datax = {
                    "usc": None,
                    "cfr": None,
                    "qa": None
                }

                # Run all searches in parallel
                threads = [
                    Thread(target=get_cfr, args=(query, datax)),
                    Thread(target=get_usc, args=(query, datax)),
                ]
                if (context[AI_TERM_SESSION_KEY] and display_qa):
                    threads.append(Thread(target=get_qa, args=(query, datax)))

                for thread in threads:
                    thread.start()

                for thread in threads:
                    thread.join()

                usc_results = datax["usc"]
                cfr_results = datax["cfr"]
                qa = datax["qa"]

                # Combine results of separate model arranged 5 each in a list
                results = []
                for i in range(0, max(len(usc_results), len(cfr_results)), 5):
                    results.extend(usc_results[i:i+5])
                    results.extend(cfr_results[i:i+5])

                context.update({
                    "nodes": results,
                    "qa": qa
                })

            elif (collection == QA) \
                    and (context[AI_TERM_SESSION_KEY] and display_qa):
                context.update({
                    "qa": make_qa(query)
                })

            else:
                COLLECTION: dict[str, Union[NodeManager, CFRNodeManager]] = {
                    settings.USCODE: Node.objects,
                    settings.CFR: CFRNode.objects,
                }

                main = COLLECTION.get(collection)
                if main:
                    context['nodes'] = main.full_text_search(query)
        return self.render_to_response(context)

    def post(self, *args, **kwargs):
        # Accept the AI generated answers term
        if self.request.POST.get("accept_ai_terms"):
            self.request.session[AI_TERM_SESSION_KEY] = True
        # Redirect to the same page
        redirect_url = self.request.META.get("HTTP_REFERER", "/")
        return redirect(redirect_url)

usc/Main/templates/Main/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800;900&display=swap"
        rel="stylesheet">

    <!-- Feather icon-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/vendors/feather-icon.css' %}">

    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    {% if title %}
    <title>DeepLegal | {{ title }}</title>
    {% else %}
    <title>DeepLegal</title>
    {% endif %}


    <link rel="icon" type="image/x-icon" href="{% static 'singularityFavicon.ico' %}">
    {% block link_css %}
    {% endblock link_css %}

    <link rel="stylesheet" type="text/css"
        href="https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.css" />
</head>

<body>

    <div id="particles-js"></div>

    <div id="main">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="/">
                    DeepLegal
                </a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <div class="ms-auto">

                        {% if request.user.is_authenticated %}
                        <a href="{% url 'account:profile' %}" class="btn btn-primary" type="submit">Account</a>
                        <a href="{% url 'account:logout' %}" class="btn btn-outline-danger ms-3" type="submit">Sign
                            out</a>
                        {% else %}
                        <a href="{% url 'account:login' %}" class="btn btn-success sign-in" type="submit">Sign in</a>
                        {% endif %}

                    </div>
                </div>
            </div>
        </nav>


        {% if messages %}
        <div class="mb-4 mt-3 container-fluid">
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endfor %}
        </div>
        {% endif %}


        <main class="container-fluid py-3">
            {% block content %}
            {% endblock %}
        </main>

        <footer>
            <div class="container-fluid py-3">
                <div class="row">
                    <div class="col-12 col-md-4 my-4 me-auto">
                        <div class="footer-logo">
                            <a href="/">
                                <img src="{% static 'deeplegal.png' %}" alt="DeepLegal" width="img-fluid">
                            </a>
                            <p>Expanding the boundaries AI assisted Legal Research.</p>
                        </div>
                    </div>
                    <div class="col-12 col-md-3 my-4">
                        <div class="footer-links">
                            <h3>Quick Links</h3>
                            <ul>
                                <li><a href="/">Home</a></li>
                                {% if request.user.is_authenticated %}
                                <li><a href="{% url 'account:profile' %}">Account</a></li>
                                <li><a href="{% url 'account:logout' %}">Logout</a></li>
                                {% else %}
                                <li><a href="{% url 'account:login' %}">Login</a></li>
                                <li><a href="{% url 'account:register' %}">Register</a></li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                    <div class="col-12 col-md-3 my-4">
                        <div class="footer-links">
                            <h3>Pages</h3>
                            <ul>
                                <li><a href="{% url 'main:terms_of_service' %}">Terms of Service</a></li>
                                <li><a href="{% url 'main:terms_of_use' %}">Terms of Use</a></li>
                                <li><a href="{% url 'main:privacy_policy' %}">Privacy Policy</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    </div>

    <form method="post" action="{% url 'main:update_cookies' %}" id="cookieForm">
        {% csrf_token %}
        <input type="hidden" name="accept">
    </form>


    <script src="https://code.jquery.com/jquery-3.6.0.js"
        integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

    <!-- Particles -->
    <script src="https://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js"></script>

    <!-- feather icon js-->
    <script src="{% static 'js/vendors/feather.min.js' %}"></script>
    <script src="{% static 'js/vendors/feather-icon.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.js" data-cfasync="false"></script>

    <script src="{% static 'js/main.js' %}"></script>

    {% block script %}
    {% endblock script %}

</body>

</html>

usc/Main/templates/Main/index.html
{% extends 'Main/base.html' %}
{% load static %}

{% block content %}

    <div id="global-search">
        <form action="{% url 'main:search' %}">

            {% include "Main/inner_search.html" %}

        </form>
    </div>

    <div id="explore-bar">
        <div class="head">

            <div class="title">
                <span>
                    <img src="{% static 'globe.png' %}" alt="">
                </span>
                Explore
            </div>

            <div class="tab-titles">
                <div class="tab-title">
                    Content
                </div>
                <div class="tab-title">
                    Federal
                </div>
                <div class="tab-title">
                    State
                </div>
                <div class="tab-title">
                    Sources
                </div>
                <div class="tab-title">
                    Topics
                </div>
                <div class="tab-title">
                    Tools
                </div>
            </div>
            
        </div>

        <div class="body">

            <p class="top">Top Sources</p>

            <div class="links">
                {% for collection in collections %}
                    <a href="/collection/{{ collection.code }}">{{ collection.name }}</a>
                {% endfor %}
            </div>

        </div>
    </div>

{% endblock %}

usc/Main/templates/Main/inner_search.html
{% load static %}
{% load utils %}

<div class="search-main">
    <legend>
        <img src="{% static 'deeplegal.png' %}" alt="">
    </legend>
    <div class="search-bar-input">
        <input type="text" name="search"
            placeholder="{% get_random_placeholder %}" class="form-control"
            value="{% if request.GET.search %}{{ request.GET.search }}{% endif %}">
        <button>
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                class="feather feather-search">
                <circle cx="11" cy="11" r="8"></circle>
                <line x1="21" y1="21" x2="16.65" y2="16.65"></line>
            </svg>
        </button>
    </div>
    <div class="search-select-bar">

        <select name="collection" id="selectCollection" class="form-select">
            <option value="">All Content</option>

            <option value="USCODE" {% if request.GET.collection == "USCODE" %} selected {% endif %}>United States Code</option>

            <option value="CFR" {% if request.GET.collection == "CFR" %} selected {% endif %}>Code of Federal Regulations</option>
           
            <option value="QA" {% if request.GET.collection == "QA" %} selected {% endif %}>Questions and Answer</option>
        </select>

        <select name="jurisdictions" id="selectJurisdiction" class="form-select">
            <option value="">All Jurisdictions</option>
        </select>

    </div>

    <p class="adv-search">Advanced Search</p>
</div>

usc/Main/templates/Main/search.html
{% extends 'Main/base.html' %}

{% block content %}

<div id="global-search">
    <form action="">
        {% include "Main/inner_search.html" %}
    </form>
</div>


{% if qa %}

<div id="ai-search" class="{% if not ai_term_accepted %}d-none{% endif %}">
    <div id="ai-result">
        {{ qa }}
    </div>
</div>

{% endif %}

{% if not ai_term_accepted %}

<div id="ai-terms">
    <h2>QA Terms</h2>
    <p>
        The information provided on this website does not, and is not intended to, constitute legal advice; instead, all
        information, content, and materials available on this site are for general informational purposes only.
        Information on this website may not constitute the most up-to-date legal or other information.
        Readers of this website should contact their attorney to obtain advice with respect to any particular legal
        matter. No reader, user, or browser of this site should act or refrain from acting on the basis of information
        on this site without first seeking legal advice from counsel in the relevant jurisdiction.
        Only your individual attorney can provide assurances that the information contained herein – and your
        interpretation of it – is applicable or appropriate to your particular situation. Use of, and access to, this
        website or any of the links or resources contained within the site do not create an attorney-client relationship
        between the reader, user, or browser and website authors, contributors, contributing law firms, or committee
        members and their respective employers.
        All liability with respect to actions taken or not taken based on the contents of this site are hereby expressly
        disclaimed. The content on this posting is provided "as is;" no representations are made that the content is
        error-free.
    </p>
    <form method="post" class="d-flex align-items-center justify-content-center gap-4">
        {% csrf_token %}
        <input type="hidden" name="accept_ai_terms" value="1">
        <button id="accept-ai-terms" class="btn btn-success">Accept</button>
        <a href="/" class="btn btn-outline-danger">Decline</a>
    </form>
</div>

{% endif %}


{% if nodes %}

<div class="main-list">
    {% for node in nodes %}
    <div class="node-item">
        <p><strong>{{ node.get_collection_name }}</strong> - {{ node.get_title }}</p>
        <div class="links">
            <a class="btn btn-sm btn-primary" href="{{ node.get_html_url }}">Paper</a>

            {% if node.pdf_link %}
            <a class="btn btn-sm btn-outline-primary" href="{{ node.pdf_link }}" target="_blank">PDF</a>
            {% endif %}
        </div>
    </div>
    {% endfor %}
</div>

{% else %}

{% if request.GET.collection != "QA" and ai_term_accepted %}
<div class="no-nodes">
    <p>Nothing to display!</p>
</div>
{% endif %}

{% endif %}


{% endblock %}

usc/Main/templates/Main/terms_of_service.html
{% extends 'Main/base.html' %}

{% block content %}

<div class="terms-container">
    <div class="terms-header">
        <h1>Terms of Service</h1>
    </div>

    <div class="terms-content">
        <p>
            These Service Terms govern your use of the Services. Capitalized terms not defined here will have the
            meanings in the Terms of Use, Enterprise Agreement, or other agreement you have with us governing your use
            of the Services (“Agreement”). If there is a conflict between the Service Terms and your Agreement, the
            Service Terms will control. For purposes of these Terms, “Content” includes “Customer Content.”
        </p>
    </div>

    <div class="terms-content">
        <h4 class="mb-3">Services</h4>
        <p class="mb-3">
            The Services on this website are offered “as-is” to allow testing and evaluation, and Content you provide
            may be used to improve the Services. The Company (Deeplegal and Singularity Dynamics, LLC) makes no
            representation or warranties for the services, including any warranty that the Services will be generally
            available, uninterrupted or error-free, or that Content will be secure or not lost or damaged. Except to the
            extent prohibited by law, the Company expressly disclaims all warranties for its Services, including any
            implied warranties of merchantability, satisfactory quality, fitness for a particular purpose,
            non-infringement, or quiet enjoyment, and any warranties arising out of any course of dealing or usage of
            trade. The Company may use third party contractors to review content for safety and moderation purposes.
        </p>
        <p>
            The Services offered by the Company are for user entertainment purposes only and should not be relied upon
            for any reason. By using the site, the user accepts all of the terms in the Terms of Service, Terms of use,
            and other agreements contained in this site.
        </p>
    </div>
</div>

{% endblock %}